Repository COVESA/vss-tools, pull requests merged in 2023-10, with the labels that each got.

#302 Removing --no-uuid
  CHANGELOG.md
  README.md
  docs/vspec2x.md
  tests/vspec/test_allowed/test_allowed.py
  tests/vspec/test_datatypes_error/test_datatypes_error.py
  tests/vspec/test_default_unit/test_default_units.py
  tests/vspec/test_include/test_include.py
  tests/vspec/test_overlay/test_overlay.py
  tests/vspec/test_overlay_on_instance/test_overlay_on_instance.py
  tests/vspec/test_overlay_struct/test_overlay_struct.py
  tests/vspec/test_overlay_struct_array/test_overlay_struct_array.py
  tests/vspec/test_struct_as_root/test_struct_as_root.py
  tests/vspec/test_structs/test_data_type_parsing.py
  tests/vspec/test_type_error/test_type_error.py
  tests/vspec/test_types_with_uuid/test_uuid.py
  tests/vspec/test_units/test_units.py
  vspec2x.py
Labels: Scope:Major, Status:Review

#296 Add jsonschema exporter for VSS.
  .pre-commit-config.yaml
  docs/vspec2x.md
  tests/vspec/test_comment/expected.jsonschema
  tests/vspec/test_datatypes/expected.jsonschema
  tests/vspec/test_generic.py
  tests/vspec/test_instances/expected.jsonschema
  vspec/vssexporters/vss2jsonschema.py
  vspec2jsonschema.py
  vspec2x.py
Labels: Status:Approved

#262 Extend existing implementation of DDSIDL exporter to support struct types.
  tests/vspec/test_structs/test.idl
  tests/vspec/test_structs/test_commandline.py
  vspec/vssexporters/vss2ddsidl.py
  vspec2x.py
Labels: Status:Review
